[phases.setup]
nixPkgs = [
    "chromium",
    "nodejs-18_x",
    "glib",
    "nss",
    "atk",
    "cups",
    "libxcomposite"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"